### ISSUE TITLE
老哥，厉害啊。打开了我的新思路。

### ISSUE THREAD

**Issue by justinlm** [spadecoder/layacannon#1]
1.没有完成的demo么。o(╥﹏╥)o
2.好像碰撞检测回调这块没有加呀。

**Comment by spadecoder** [comment]
是没有完成，但是有碰撞检测回调哦

**Comment by justinlm** [comment]
哦，我看到的是CannonSimulation 的_eventScripts 里面scriptsA[j].onTriggerStay(colliderB); 这块被你注释掉了。脚本层接收回调这块没看到在哪了，o(╥﹏╥)o

**Comment by spadecoder** [comment]
请看CannonSimulation.emitEvent方法的实现
