### ISSUE TITLE
老哥这么快把我Issue关了啊，我还想问下你的cannon用的是哪个呢

### ISSUE THREAD

**Issue by justinlm** [spadecoder/layacannon#2]
老哥你用的cannon是你们自己改过的么，好像不是关schteppe的那个。看见有api是schteppe的那个是没有的。比如 CannonSimulation 的_eventScripts方法里调用的
this.world.emitTriggeredEvents();
this.world.emitCollisionEvents();

**Comment by spadecoder** [comment]
用的cocos creator3d的版本
https://github.com/cocos-creator/cannon.js

**Comment by justinlm** [comment]
明白了。研究中。谢谢
